[package]
name = "ittech"
version = "0.1.0"
description = "Impulse Tracker file parser and writer"
authors = []
edition = "2018"

[dependencies]
bitflags = "1.2"
nom = "6.0"

[dev-dependencies]
anyhow = "1.0"
hound = "3.4"
